#!/usr/bin/env Rscript

get_script_path <- function() {
  file_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(file_arg) == 0) return(NA_character_)
  normalizePath(sub("^--file=", "", file_arg[[1]]), winslash = "/", mustWork = TRUE)
}

script_path <- get_script_path()
if (is.na(script_path)) {
  stop("Could not determine script path (expected Rscript --file=...)", call. = FALSE)
}

script_dir <- dirname(script_path)
pkg_dir <- normalizePath(file.path(script_dir, ".."), winslash = "/", mustWork = TRUE)
repo_dir <- normalizePath(file.path(pkg_dir, "..", ".."), winslash = "/", mustWork = TRUE)
datasets_dir <- normalizePath(file.path(repo_dir, "datasets"), winslash = "/", mustWork = TRUE)

if (!dir.exists(datasets_dir)) {
  stop("Datasets folder not found: ", datasets_dir, call. = FALSE)
}

csv_paths <- sort(list.files(datasets_dir, pattern = "\\.csv$", full.names = TRUE, ignore.case = TRUE))
if (length(csv_paths) == 0) {
  stop("No CSV files found in: ", datasets_dir, call. = FALSE)
}

ensure_pkg <- function(pkg) {
  if (requireNamespace(pkg, quietly = TRUE)) return(invisible(TRUE))
  message("Installing missing build dependency: ", pkg)
  install.packages(pkg, repos = "https://cloud.r-project.org")
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Failed to install required package: ", pkg, call. = FALSE)
  }
  invisible(TRUE)
}

ensure_pkg("usethis")

suppressMessages(usethis::proj_set(pkg_dir))

datasets <- list()
seen_names <- new.env(parent = emptyenv())

for (csv_path in csv_paths) {
  source_file <- basename(csv_path)
  name_raw <- tools::file_path_sans_ext(source_file)
  name <- name_raw

  if (!identical(make.names(name), name)) {
    name <- make.names(name)
  }

  if (!identical(make.names(name), name)) {
    stop("Could not derive a valid R object name from: ", name_raw, call. = FALSE)
  }

  if (exists(name, envir = seen_names, inherits = FALSE)) {
    stop("Duplicate dataset name detected: ", name, call. = FALSE)
  }
  assign(name, TRUE, envir = seen_names)

  obj <- utils::read.csv(csv_path, stringsAsFactors = FALSE, check.names = FALSE)

  e <- new.env(parent = baseenv())
  assign(name, obj, envir = e)
  eval(parse(text = sprintf("usethis::use_data(%s, overwrite = TRUE)", name)), envir = e)

  datasets[[length(datasets) + 1]] <- list(name = name, source_file = source_file)
}

# Generate roxygen dataset docs and the dataset name list consumed by .onLoad().
docs_path <- file.path(pkg_dir, "R", "data-datasets.R")

dataset_names <- vapply(datasets, function(d) d$name, character(1))

lines <- character(0)
lines <- c(lines, "# Generated by data-raw/build_data.R: do not edit by hand")
lines <- c(lines, "")
quoted_names <- paste(sprintf("\"%s\"", dataset_names), collapse = ", ")
lines <- c(lines, sprintf("pythonly_dataset_names <- c(%s)", quoted_names))
lines <- c(lines, "")

for (d in datasets) {
  nm <- d$name
  src <- d$source_file

  lines <- c(lines, sprintf("#' %s dataset", nm))
  lines <- c(lines, "#'")
  lines <- c(lines, sprintf("#' Imported from `%s`.", file.path("datasets", src)))
  lines <- c(lines, "#'")
  lines <- c(lines, "#' @docType data")
  lines <- c(lines, sprintf("#' @name %s", nm))
  lines <- c(lines, "#' @keywords datasets")
  lines <- c(lines, sprintf("\"%s\"", nm))
  lines <- c(lines, "")
}

dir.create(dirname(docs_path), recursive = TRUE, showWarnings = FALSE)
writeLines(lines, docs_path, useBytes = TRUE)

message("Built datasets: ", paste(dataset_names, collapse = ", "))
message("Wrote roxygen docs: ", docs_path)
message("Next: devtools::document('", pkg_dir, "')")

